name: "yolo11n"
platform: "tensorrt_plan"
max_batch_size: 4
default_model_filename: "model.plan"

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [84, 8400]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]

dynamic_batching {
  preferred_batch_size: [1, 2, 4]
  max_queue_delay_microseconds: 100
}

optimization {
  cuda {
    graphs: true
    graph_spec [
      {
        batch_size: 1
        input {
          key: "images"
          value {
            dim: [3, 640, 640]
          }
        }
      }
    ]
  }
}
